### PR TITLE
Enrolment added to conf

### PR DESCRIPTION
**Pull request by Callustian**
Hi Allan,

This setting should solve the issue.

Thanks and apologies,

Pasquale

### CODE REVIEW

**Comment by michzimny** [comment]
I suspect, "the issue" is #107.

@athird, could you please review?

**Comment by Callustian** [comment]
Moodle 3.6.2 tackles the problem using other settings

**Comment by Callustian** [comment]
I apologise I think this is needed.

**Comment by Callustian** [comment]
I am adding this to rel 004. Not merging to this to master.

**Pull request closed without merging**
