### PR TITLE
New block_category_enrol plugin

### PR DESCRIPTION
**Pull request by nadavkav**
New configuration update for adding block_category_enrol into Moodle, via blocks/category_enrol
(updates Dockerfile)
Allow auto enrollment of any course role into the course category as well, with any selected role.

### CODE REVIEW

**Comment by michzimny** [comment]
@nadavkav, coud we point the dependency to its specific version (not just master branch) as in my latest commit here?

We have already experienced that we need to be able to easily rollback to a previous version of our Moodle setup, and that we don't want to be surprised with 'self-updating' dependencies. If a dependency needs an upgrade, we need a new commit to this repository (e.g. changing provided commit SHA), not just a commit to the plugin's repository.

**Comment by nadavkav** [comment]
Agree (me bad)

**Comment by michzimny** [comment]
@nadavkav, I fogot we also need to provide the proper configuration for the tool.

Could you please follow Allan's instructions to provide necessary settings: https://wiki.geant.org/pages/viewpage.action?pageId=99483907

**Comment by nadavkav** [comment]
There is no system wide settings for this plugin, thought it has a per instance settings. but it needs to be configured on a per course bases. i.e, for each course the block is added, the person adding the block need to set the in course role1 assignment the block is following and the category auto role2 assignment that is linked to it.

**Comment by michzimny** [comment]
Ok, that's fine. Thank you.

**Pull request merged**
