### PR TITLE
New plugin questionnaire

### PR DESCRIPTION
**Pull request by michzimny**

### CODE REVIEW

**Comment by michzimny** [comment]
I'm not sure whether the changes to .env and .scsv files are correct. Why you have there some KNOCKPLOP variables?

**Comment by ivanoterouvigo** [comment]
@michzimny, It's true. I've submited some changes.
I put the same vars than knockplot plugin.

For trying to be sure. I followed steps of this guide:

https://github.com/up2university/docker-moodle

I had an error in step; 

**docker-compose build**

ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

What do I need to do now?

**Comment by michzimny** [comment]
@athird, @ivanoterouvigo, what's the status regarding this? Is it to be cancelled and closed?

**Comment by michzimny** [comment]
Please reopen if needed.

**Pull request closed without merging**
