### PR TITLE
108 add hyperlinks on the contact section

### PR DESCRIPTION
**Pull request by msbachler**

### CODE REVIEW

**Comment by michzimny** [comment]
Are THEME_FORDSON_SOCIAL1 and THEME_FORDSON_SOCIAL1_ICON new env vars? Shouldn't they be set in the env repo in order to not to break any deployment on missing values?

Or, if we are going to set them to the same values in all instance, then perhaps we could either provide default values here or hard-code the values?

**Comment by msbachler** [comment]
Sorry, missed your question. I asume you found the 108 branch I put in the env repository.

**Comment by michzimny** [comment]
Sorry, I found the pull requests in the env repo just now. You can assign me there as reviewer too so I will get notifications.

**Comment by msbachler** [comment]
Sorry. Yes, Allan showed me before and I forgot to do that part.

Michelle

**Pull request merged**
