### PR TITLE
Knockplop plugin

### PR DESCRIPTION
**Pull request by misi**
Please review..

### CODE REVIEW

**Comment by misi** [comment]
ping..

**Comment by michzimny** [comment]
Branch master is our production branch, and branch develop is for development and for staging environment. We probably should merge into develop, right? Moreover, in develop we have Moodle 3.3 - maybe some changes are needed.

**Comment by misi** [comment]
Cześć! @michzimny

It is not clear what is this project branching philosophy..
Could you help me out and describe the right process?
(e.g. http://nvie.com/posts/a-successful-git-branching-model/)

I thought devel is the feature branch, so I made my own feature  and submitted the PR.
You mean we don't use feature branches only one devel? 
IMHO it is a confusing this branching model if more people develop more features like it occurred.

Anyhow I submitted separated commits from the beginning:
And it is very simple https://github.com/up2university/docker-moodle/pull/14/commits/385a67db5456d17bd1eda10ed7e0daa82fdae14b it probably could be applied onto even dev.
Furthermore the modul I have tested with moodle 3.3 too.
So could you please rebase my commit onto dev or fork the dev and create 3.3 feature branch and also a branch for knockplop?

**Comment by michzimny** [comment]
Hi @misi,
the branching model is the same as in that article you linked to. The master branch holds production-ready state. The develop branch is the latest development state, which is considered ready to be moved to production on the next release (i.e. merged into master). The develop branch is not feature branch. Feature branches are to be merged into develop, as in that article.

You've created this PR to master, so it cannot be accepted, because your changes should not go to production right now. It should be a PR to develop first. I can make the change right now.

Then, we probably need @athird's review...

Cheers!

**Comment by michzimny** [comment]
However now, some conflicts are to be solved :)

**Pull request merged**
