### PR TITLE
Auto config

### PR DESCRIPTION
**Pull request by michzimny**
et's keep the PR open to easily track changes in the branch. We merge it once it's ready.

### CODE REVIEW

**Comment by michzimny** [comment]
But I'm not sure whether it's ready...

**Comment by michzimny** [comment]
I just disabled auto deployment to learn.test as we rather don't want it yet.

**Comment by athird** [comment]
Ah, sorry. :-( I thought I was just merging your filename changes, that's all it showed in the diff.

**Comment by michzimny** [comment]
It's ok, I'm almost ready with the deployment script.

**Pull request merged**
