### PR TITLE
PuMoodle Feature: PuMuKIT integracion.

### PR DESCRIPTION
**Pull request by rubenrua**
This two need plugins are necesary to display the videos of portal.oer.geant.org as a repository:

* **pmksearch.zip**: Add a new media repository with the contents of a PuMuKIT instance (portal.oer.geant.org in this case)

PuMoodle Repository

* **filter.zip**:  PuMuKIT media embedding filter that replace the URL added by the repository into the player.

tres

### CODE REVIEW

**Comment by athird** [comment]
The Travis build fails (log here: https://api.travis-ci.org/jobs/245872341/log.txt?deansi=true) - this looks like the relevant part: 

Step 47/51 : RUN cd /var/www/html/filter/; unzip filter.zip
 ---> Running in ebfbb74da52c
Archive:  filter.zip
   creating: pumukit/
  inflating: pumukit/readme.txt      
  inflating: pumukit/filtersettings.php  
  inflating: pumukit/version.php     
   creating: pumukit/lang/
   creating: pumukit/lang/en/
  inflating: pumukit/lang/en/filter_pumukit.php  
  inflating: pumukit/filter.php      
 ---> c09b7160a27f
Removing intermediate container ebfbb74da52c
Step 48/51 : ADD ./pumoodle/pmksearch.zip /var/www/html/search/pmksearch.zip
 ---> f4cb79938031
Removing intermediate container 0324371268be
Step 49/51 : RUN cd /var/www/html/repository/; unzip pmksearch.zip
 ---> Running in 8b1b279e2b4b
unzip:  cannot find or open pmksearch.zip, pmksearch.zip.zip or pmksearch.zip.ZIP.
The command '/bin/sh -c cd /var/www/html/repository/; unzip pmksearch.zip' returned a non-zero code: 9

**Comment by rubenrua** [comment]
@athird fixed.  (We only wanted  to test the CI :))

**Comment by rubenrua** [comment]
In the moodle `Dockerfile`  zips files are downloaded from moodle site and github site. However, we added it inside the repo.

If you prefer we change it, we can download our zips from github too.

Please let us know.

**Comment by athird** [comment]
Good test, the CI is working. :-)

I don't mind if we have the zips inside the repo or not, whichever you think is best. I'll merge this now as it is, we could always change it later if you think it's better to pull them from Github.

**Pull request merged**
